// ============================================================
// 狼人杀游戏常量定义
// ============================================================

// ---- 角色定义 ----
export const ROLES = {
  WEREWOLF: 'WEREWOLF',           // 普通狼人
  ALPHA_WOLF: 'ALPHA_WOLF',       // 种狼
  SEER: 'SEER',                   // 预言家
  POISON_WITCH: 'POISON_WITCH',   // 毒巫（烈性毒药）
  HEAL_WITCH: 'HEAL_WITCH',       // 药巫（万能药）
  VILLAGER: 'VILLAGER',           // 村民
  GUARD: 'GUARD',                 // 守卫
  HUNTER: 'HUNTER',               // 猎人
};

// 角色阵营
export const TEAMS = {
  WOLF: 'WOLF',       // 狼人阵营
  VILLAGE: 'VILLAGE', // 好人阵营
};

// 每个角色所属阵营
export const ROLE_TEAM = {
  [ROLES.WEREWOLF]: TEAMS.WOLF,
  [ROLES.ALPHA_WOLF]: TEAMS.WOLF,
  [ROLES.SEER]: TEAMS.VILLAGE,
  [ROLES.POISON_WITCH]: TEAMS.VILLAGE,
  [ROLES.HEAL_WITCH]: TEAMS.VILLAGE,
  [ROLES.VILLAGER]: TEAMS.VILLAGE,
  [ROLES.GUARD]: TEAMS.VILLAGE,
  [ROLES.HUNTER]: TEAMS.VILLAGE,
};

// 角色中文名
export const ROLE_NAMES = {
  [ROLES.WEREWOLF]: '狼人',
  [ROLES.ALPHA_WOLF]: '种狼',
  [ROLES.SEER]: '预言家',
  [ROLES.POISON_WITCH]: '毒巫',
  [ROLES.HEAL_WITCH]: '药巫',
  [ROLES.VILLAGER]: '村民',
  [ROLES.GUARD]: '守卫',
  [ROLES.HUNTER]: '猎人',
};

// 角色图标（emoji占位，后续替换为插图）
export const ROLE_ICONS = {
  [ROLES.WEREWOLF]: '🐺',
  [ROLES.ALPHA_WOLF]: '👑🐺',
  [ROLES.SEER]: '🔮',
  [ROLES.POISON_WITCH]: '☠️🧪',
  [ROLES.HEAL_WITCH]: '💚🧪',
  [ROLES.VILLAGER]: '👨‍🌾',
  [ROLES.GUARD]: '🛡️',
  [ROLES.HUNTER]: '🔫',
};

// ---- 游戏阶段 ----
export const PHASES = {
  LOBBY: 'LOBBY',             // 等待大厅
  NIGHT: 'NIGHT',             // 夜晚阶段
  DAY: 'DAY',                 // 白天讨论阶段
  VOTE: 'VOTE',               // 投票阶段
  GAME_OVER: 'GAME_OVER',     // 游戏结束
};

// 夜晚子步骤（按行动顺序）
export const NIGHT_STEPS = {
  HUNTER: 'HUNTER',           // 猎人（第二晚起第一位）
  ALPHA_WOLF: 'ALPHA_WOLF',   // 种狼
  GUARD: 'GUARD',             // 守卫
  WEREWOLF: 'WEREWOLF',       // 狼人群
  SEER: 'SEER',               // 预言家
  POISON_WITCH: 'POISON_WITCH', // 毒巫
  HEAL_WITCH: 'HEAL_WITCH',   // 药巫
  RESOLUTION: 'RESOLUTION',   // 结算
};

// 第一晚行动顺序（无猎人）
export const NIGHT_STEPS_NIGHT1 = [
  NIGHT_STEPS.ALPHA_WOLF,
  NIGHT_STEPS.GUARD,
  NIGHT_STEPS.WEREWOLF,
  NIGHT_STEPS.SEER,
  NIGHT_STEPS.POISON_WITCH,
  NIGHT_STEPS.HEAL_WITCH,
  NIGHT_STEPS.RESOLUTION,
];

// 第二晚起行动顺序（猎人在最前）
export const NIGHT_STEPS_FULL = [
  NIGHT_STEPS.HUNTER,
  NIGHT_STEPS.ALPHA_WOLF,
  NIGHT_STEPS.GUARD,
  NIGHT_STEPS.WEREWOLF,
  NIGHT_STEPS.SEER,
  NIGHT_STEPS.POISON_WITCH,
  NIGHT_STEPS.HEAL_WITCH,
  NIGHT_STEPS.RESOLUTION,
];

// ---- 夜晚行动选项 ----
export const NIGHT_ACTIONS = {
  GO_OUT: 'GO_OUT',           // 出门
  USE_ABILITY: 'USE_ABILITY', // 使用能力
  SLEEP: 'SLEEP',             // 睡觉（留在家中）
};

// ---- 种狼能力子选项 ----
export const ALPHA_ACTIONS = {
  TRANSFORM: 'TRANSFORM',     // 变狼
  INFECT: 'INFECT',           // 感染
  KILL: 'KILL',               // 刀人（需先变狼）
};

// ---- 猎人武器 ----
export const HUNTER_WEAPONS = {
  RIFLE: 'RIFLE',             // 猎枪
  BLUNDERBUSS: 'BLUNDERBUSS', // 短火铳
};

// ---- 角色分类（用于移动规则） ----
export const MOVE_TYPES = {
  FREE: 'FREE',               // 不受限制（狼人/守卫/猎人）
  RESTRICTED: 'RESTRICTED',   // 只能去别人家（神/村民）
};

// 哪些角色出门不计入屋内人数
export const NOT_COUNT_IN_HOUSE = [ROLES.WEREWOLF, ROLES.ALPHA_WOLF];

// "守护姿态的守卫"也不计入 —— 通过状态判断

// 可以自由移动的角色（出门不限于去别人家）
export const FREE_MOVERS = [ROLES.HUNTER, ROLES.WEREWOLF, ROLES.ALPHA_WOLF, ROLES.GUARD];

// ---- 预设角色配置（按玩家人数） ----
export const ROLE_CONFIGS = {
  5: [ROLES.ALPHA_WOLF, ROLES.WEREWOLF, ROLES.SEER, ROLES.HEAL_WITCH, ROLES.VILLAGER],
  6: [ROLES.ALPHA_WOLF, ROLES.WEREWOLF, ROLES.SEER, ROLES.POISON_WITCH, ROLES.VILLAGER, ROLES.VILLAGER],
  7: [ROLES.ALPHA_WOLF, ROLES.WEREWOLF, ROLES.SEER, ROLES.POISON_WITCH, ROLES.HEAL_WITCH, ROLES.VILLAGER, ROLES.VILLAGER],
  8: [ROLES.ALPHA_WOLF, ROLES.WEREWOLF, ROLES.SEER, ROLES.POISON_WITCH, ROLES.HEAL_WITCH, ROLES.GUARD, ROLES.VILLAGER, ROLES.VILLAGER],
  9: [ROLES.ALPHA_WOLF, ROLES.WEREWOLF, ROLES.WEREWOLF, ROLES.SEER, ROLES.POISON_WITCH, ROLES.HEAL_WITCH, ROLES.GUARD, ROLES.VILLAGER, ROLES.VILLAGER],
  10: [ROLES.ALPHA_WOLF, ROLES.WEREWOLF, ROLES.WEREWOLF, ROLES.SEER, ROLES.POISON_WITCH, ROLES.HEAL_WITCH, ROLES.GUARD, ROLES.HUNTER, ROLES.VILLAGER, ROLES.VILLAGER],
  11: [ROLES.ALPHA_WOLF, ROLES.WEREWOLF, ROLES.WEREWOLF, ROLES.SEER, ROLES.POISON_WITCH, ROLES.HEAL_WITCH, ROLES.GUARD, ROLES.HUNTER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER],
  12: [ROLES.ALPHA_WOLF, ROLES.WEREWOLF, ROLES.WEREWOLF, ROLES.SEER, ROLES.POISON_WITCH, ROLES.HEAL_WITCH, ROLES.GUARD, ROLES.HUNTER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER],
  13: [ROLES.ALPHA_WOLF, ROLES.WEREWOLF, ROLES.WEREWOLF, ROLES.SEER, ROLES.POISON_WITCH, ROLES.HEAL_WITCH, ROLES.GUARD, ROLES.HUNTER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER],
  14: [ROLES.ALPHA_WOLF, ROLES.WEREWOLF, ROLES.WEREWOLF, ROLES.SEER, ROLES.POISON_WITCH, ROLES.HEAL_WITCH, ROLES.GUARD, ROLES.HUNTER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER],
  15: [ROLES.ALPHA_WOLF, ROLES.WEREWOLF, ROLES.WEREWOLF, ROLES.SEER, ROLES.POISON_WITCH, ROLES.HEAL_WITCH, ROLES.GUARD, ROLES.HUNTER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER],
  16: [ROLES.ALPHA_WOLF, ROLES.WEREWOLF, ROLES.WEREWOLF, ROLES.WEREWOLF, ROLES.SEER, ROLES.POISON_WITCH, ROLES.HEAL_WITCH, ROLES.GUARD, ROLES.HUNTER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER],
  17: [ROLES.ALPHA_WOLF, ROLES.WEREWOLF, ROLES.WEREWOLF, ROLES.WEREWOLF, ROLES.SEER, ROLES.POISON_WITCH, ROLES.HEAL_WITCH, ROLES.GUARD, ROLES.HUNTER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER],
  18: [ROLES.ALPHA_WOLF, ROLES.WEREWOLF, ROLES.WEREWOLF, ROLES.WEREWOLF, ROLES.SEER, ROLES.POISON_WITCH, ROLES.HEAL_WITCH, ROLES.GUARD, ROLES.HUNTER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER, ROLES.VILLAGER],
};

// 获取指定人数的推荐角色配置
export function getRoleConfig(playerCount) {
  return ROLE_CONFIGS[playerCount] || ROLE_CONFIGS[12];
}
